# Generated by Django 4.0.6 on 2022-08-02 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_userlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='product.product'),
        ),
        migrations.AlterUniqueTogether(
            name='userlesson',
            unique_together={('user', 'lesson')},
        ),
    ]
